package com.adityainfotech.societyms.domain.entity;

import com.adityainfotech.societyms.domain.enums.ApprovalStatus;
import com.adityainfotech.societyms.domain.enums.PaymentMode;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * A payment against a maintenance bill.
 *
 * Approval workflow:
 *   Member submits  → approvalStatus = PENDING  (bill stays PENDING)
 *   Admin approves  → approvalStatus = APPROVED → bill.status = PAID
 *   Admin pays      → approvalStatus = APPROVED  (direct, no PENDING step)
 *   Admin rejects   → approvalStatus = REJECTED  (bill stays PENDING, member can retry)
 *
 * receipt_number is generated by ReceiptSequenceService using the pattern:
 *   RCPT-YYYYMM-XXXX  (e.g. RCPT-202504-0042)
 * It is set before persist and is globally unique.
 */
@Entity
@Table(name = "payments")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bill_id", nullable = false)
    private MaintenanceBill bill;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    private Member member;

    @Column(name = "amount_paid", nullable = false, precision = 10, scale = 2)
    private BigDecimal amountPaid;

    @Column(name = "payment_date", nullable = false)
    private LocalDate paymentDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_mode", nullable = false, length = 20)
    private PaymentMode paymentMode;

    @Column(name = "reference_no", length = 100)
    private String referenceNo;

    /** Auto-generated: RCPT-YYYYMM-XXXX */
    @Column(name = "receipt_number", unique = true, length = 50)
    private String receiptNumber;

    @Column(length = 500)
    private String remarks;

    @Enumerated(EnumType.STRING)
    @Column(name = "approval_status", nullable = false, length = 20)
    @Builder.Default
    private ApprovalStatus approvalStatus = ApprovalStatus.PENDING;

    /** FK → users.id: who approved/rejected this payment. */
    @Column(name = "approved_by")
    private Long approvedBy;

    @Column(name = "approved_at")
    private LocalDateTime approvedAt;

    @Column(name = "rejection_reason", length = 300)
    private String rejectionReason;

    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    public void prePersist() {
        this.createdAt = LocalDateTime.now();
    }
}
